### PR TITLE
chore(space-wizard): refactor rename and move files

### PR DESCRIPTION
**Pull request by mitchharpur**
- add app-generator-single-input components to wizard
- move facric8serviceclient to services folder for better functional proximity
- simplify app-generator html
- rename and move files out of **/concrete/** folders and update relevant dependencies

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1458-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1458-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1458-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
