### PR TITLE
fix(space-wizard): add stack augmented text and several ux updates 

### PR DESCRIPTION
**Pull request by mitchharpur**
- augment stack dropdown text and order
- augment pipeline drop down text
- progress indicators
- validation improvements
- ux style improvements  as per ux feedback

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f829c03a5cdf9f664fea5012b178f99e9d699eff
  * Your subject line is longer than 50 characters

 * Commit: eb630fb9884ab144b217dcb803966b0089f75939
  * Your subject line is longer than 50 characters

 * Commit: 024456b27aace8728c6e37a7d04d4eba9fb75b4e
  * Your subject line is longer than 50 characters

 * Commit: 6654be58dd60d30c30ada2d8c9ae086200b5e5b9
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1026-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
Same issue with the Next button

**Pull request merged**
