### PR TITLE
fix(login): remove public

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d3e0b5a2a846ad3aae09d769fb27ef0d257bc7c0
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d35bbe814a9db3049ae1bea0ac55d025342488b3
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
@pmuir there is 'public' as a reserved word in dummy.service that you don't need anymore. But that is something you can clean up another time.

**Pull request merged**
