### PR TITLE
fix(planner): refactored to use the new Planner library layout.

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Applies changes to the Platform code to get it working with the new Planner source layout.

Please do not merge until the Planner CI/CD is working again. I'll let you know when we have that in place.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6ea9eb4355a6b097f5c644290bdc09af789d5489
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0c7d56777f1c55dc60ce96c6150dd7fafc537ca
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0c7d56777f1c55dc60ce96c6150dd7fafc537ca
  * Your subject line is longer than 50 characters

 * Commit: e7aab6915bb5ba23108d5ed5c180222dd9bb0ef6
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e0c7d56777f1c55dc60ce96c6150dd7fafc537ca
  * Your subject line is longer than 50 characters

 * Commit: e7aab6915bb5ba23108d5ed5c180222dd9bb0ef6
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1389-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
