### PR TITLE
feat(Home): Update HTML for home dashboard

### PR DESCRIPTION
**Pull request by SMahil**
Update HTML for home dashboard

Wireframes: https://redhat.invisionapp.com/share/XZAOBAOPB#/screens/221480596

Screenshots:
screen shot 2017-04-13 at 12 53 29 pm

screen shot 2017-04-13 at 12 54 20 pm

### CODE REVIEW

**Comment by SMahil** [comment]
@catrobson @mindreeper2420 This is as per patternfly classes which deviates a bit from UX designs. LMK if its good to go

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-719.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@SMahil will there be logic in the Spaces card to show/hide the 'Create a space' that is in the title area if only the blank-state view is shown?

**Comment by SMahil** [comment]
@mindreeper2420 I didn't add that stuff. Its just plain HTML yet.

**Pull request merged**
