### PR TITLE
chore(space-wizard): refactor wizard into smaller components

### LINKED ISSUE #862: Space Wizard has the same tooltip/title message everywhere
No matter where I hover my mouse in the Space Wizard, I am presented with a tooltip/title message of 'Create new space'. If tooltips/title messages are used, they should be specific to given click points ('X' for close, buttons, etc.).

screen shot 2017-04-19 at 9 57 27 am

### PR DESCRIPTION
**Pull request by mitchharpur**
- Refactor wizard page into smaller components to make it easier to understand and remove some more tech debt
- Make styles on wizard forge panel ( now a separate component) more compliant to ux mockups
- Remove some redundant classes 
- Add tooltips to app generator fields page

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3a294ae4b2c8dc50e501ea16bf5d42ff9dfedfae
  * Your subject line is longer than 50 characters

 * Commit: 0bfb2aec0c56799e203b4421287fb01d6748ab31
  * Your subject line is longer than 50 characters

 * Commit: 409238122ecc5c84e523caa1517805ef75d2fcc8
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@rawlingsj do you know why this is failing to build?

@mitchharpur please rebase

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 87b41b3e06df8bdc23031f82430e757021d3b253
  * Your subject line is longer than 50 characters

 * Commit: da633234cdbd449fb94026bc2ceef6e6f67eeee1
  * Your subject line is longer than 50 characters

 * Commit: 6309e43c4a2637bef8e5866cebbe2bb020a75d77
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1392-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
