### PR TITLE
feat: space-wizard-forge-integration -part-1

### PR DESCRIPTION
**Pull request by mitchharpur**
Initial integration bits of space wizard using forge api. Still needs more ui parts but the forge api is being called. Just about all the files are in the space wizard folder to be as stand alone as possible... with a view to building an npm module.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 146093580ec88f86e6ecd23cdaf19238c40bd765
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 146093580ec88f86e6ecd23cdaf19238c40bd765
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8b08e8c88136399c9f79608465e0826a52029379
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 146093580ec88f86e6ecd23cdaf19238c40bd765
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8b08e8c88136399c9f79608465e0826a52029379
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@mitchharpur there are compile errors. Please fix those.

**Comment by mitchharpur** [comment]
kill this pr ... no need .. replaced by another pr feat(space-wizard-forge)

**Pull request closed without merging**
