### PR TITLE
feat(collaborators): add collaborators to space settings

### PR DESCRIPTION
**Pull request by dgutride**

### CODE REVIEW

**Comment by sbose78** [comment]
Hi @dgutride ,
How are you populating the list currently? I suppose you are using the existing `userService.getAllUsers()` ? While this is fine for now - we would eventually have problems with scaling this :) So, I have a PR for 'searching' a user ( which can be be implemented on the UX side as a type-ahead. ) : https://github.com/almighty/almighty-core/pull/1242

**Comment by fabric8cd** [comment]
@dgutride snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1048-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by catrobson** [comment]
@dgutride - a few comments for improvement:

- The add modal shouldn't need to be so large.  Can we decrease the vertical height and just have the dropdown overlay past the modal bottom?
image
- Is there a way for the dropdown to only contain users who have not been added?
- When I hover over a row, the e-mail is getting a white background
image
- Probably need to add the word "space" after putting the space name in the remove dialog.  The cancel button also should be a normal PatternFly button, this looks like an odd gray button color.
image
- I think clicking on the row should also bring me to "View user" (profile)
-

**Pull request merged**
