### PR TITLE
Component.unit.tests

### PR DESCRIPTION
**Pull request by corinnekrych**
Add component test for codeservices as part of https://github.com/fabric8io/fabric8-ui/issues/1238

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3787a2ce87af1e98aa670cbbe15dfb506c5cb2d7
  * Your subject line is longer than 50 characters

 * Commit: 1898d08a7b39468a636b108a19eb6040381e72d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7f0f295e764d7a25bedce50b2369337e99b49b40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e2acb1dd2e17c259806313449610a14253a07d0c
  * Your subject line is longer than 50 characters

 * Commit: eb81991585a4a92761e82cc1bbe808e81d929e38
  * Your subject line is longer than 50 characters

 * Commit: a22c7a9fd2c7ae1972bb93d0832e3b93c7ed457a
  * Your subject line is longer than 50 characters

 * Commit: 847d0526d3ef722cf57991a6af48bb4b17a98909
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3787a2ce87af1e98aa670cbbe15dfb506c5cb2d7
  * Your subject line is longer than 50 characters

 * Commit: 1898d08a7b39468a636b108a19eb6040381e72d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7f0f295e764d7a25bedce50b2369337e99b49b40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e2acb1dd2e17c259806313449610a14253a07d0c
  * Your subject line is longer than 50 characters

 * Commit: eb81991585a4a92761e82cc1bbe808e81d929e38
  * Your subject line is longer than 50 characters

 * Commit: a22c7a9fd2c7ae1972bb93d0832e3b93c7ed457a
  * Your subject line is longer than 50 characters

 * Commit: 847d0526d3ef722cf57991a6af48bb4b17a98909
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1315-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3787a2ce87af1e98aa670cbbe15dfb506c5cb2d7
  * Your subject line is longer than 50 characters

 * Commit: 1898d08a7b39468a636b108a19eb6040381e72d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7f0f295e764d7a25bedce50b2369337e99b49b40
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e2acb1dd2e17c259806313449610a14253a07d0c
  * Your subject line is longer than 50 characters

 * Commit: eb81991585a4a92761e82cc1bbe808e81d929e38
  * Your subject line is longer than 50 characters

 * Commit: a22c7a9fd2c7ae1972bb93d0832e3b93c7ed457a
  * Your subject line is longer than 50 characters

 * Commit: 847d0526d3ef722cf57991a6af48bb4b17a98909
  * Your subject line is longer than 50 characters

 * Commit: ce1b9f8b9899bbd965e000fb8b23a69bb6722f3b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1315-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
