### PR TITLE
feat(): Added functionality to profile page

### PR DESCRIPTION
**Pull request by dlabrecq**
Modified left side column show different states when there are no profile image, email, url, and/or bio values.
Clicking on empty profile image, email, url or bio takes user to edit profile page and sets focus on associated input element.
Modified spaces tab to show a list of 10 spaces with an infinite scroll to fetch more.
Modified work items to show a list of 10 recently assigned work items.
Modified activity tab to show a list of 10 recent (dummy) activities.
Added an empty state for activity, spaces, and work tabs.
Added feature to allow user to delete space from list per Catherine's request.
User can add space from empty state.

Layout and features are based on latest mockup from @jryhanyc:
https://redhat.invisionapp.com/share/KQB6LEHM8#/screens/227580206

Reviewed with @catrobson 

Notes:

1. Some functionality depends on https://github.com/fabric8io/fabric8-ui/pull/1263. For example, clicking on links for "Add email", "Add bio", etc.

2. The total number of spaces is not shown in the spaces tab (per mockups) because the spaces list is an infinite scroll -- the API does not provide a total number of spaces.

3. Activities are not currently supported by the APIs -- screenshot shows dummy data. However, WorkItems, WorkItemLinks and Comments have history stored in the backend. Will hook this up when it becomes available.

Activity Tab:
activity

No activity:
activity-none

Spaces Tab:
spaces

No spaces:
spaces-none

Work Items Tab:
work items

No work items:
work-items-none

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1291-fabric8-ui.int.rdu2c.fabric8.io

**Comment by catrobson** [comment]
@jryhanyc and @dlabrecq - Few follow-up items for improvement:

- Should we use full name instead of username for the headers?
- Need a pagination mechanism for spaces
- Need to discuss options for profile images.  Can we support image storage to upload one?  The linking process feels unexpected.

**Comment by dlabrecq** [comment]
For the Spaces tab, I ended up using an infinite scroll feature. This is the same approach used elsewhere in the UI (e.g., for the planner tree list and "View all spaces" page). 

The way this works here is 20 rows are fetched initially, but only 10 are visible. As the user scrolls, more rows are fetched as needed.

Regarding the full name Vs username; we're guaranteed to have a username, while the full name is optional. We might consider using different text like "My spaces" Vs "Dan Labrecque's spaces"?

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1291-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1291-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1291-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
