### PR TITLE
feature(ci): CI pipeline to unit test and deploy …

### PR DESCRIPTION
**Pull request by rawlingsj**
…snapshot console on pull requests

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 52ff38d317ce08f30bfc6300dfa011880af675ba
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0a543801057a19bcdd26a09205db821acf3394c4
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-668.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 03185b51a2bdc74a1d7da15611a0113558a231fe
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-668.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
