### PR TITLE
reproducer: use matrix parameters for routing

### PR DESCRIPTION
**Pull request by pmuir**
DO NOT MERGE

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 14fce4f41541ea032c57ffcf797f71f4316fd7e0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
@sanbornsen @joshuawilson @michaelkleinhenz @maxandersen here is a simple of example of how you can use matrix parameters for routing whilst still lazy loading children. It uses a custom matcher to achieve this.

Note that order matters with the routes (as it always does) and that you can't do this on a route with no path (i.e. put plan on a parent - this causes some 'undefined' errors). This would need making more robust, and all links etc. updating to end with ;view=board when using the board view.

Note that I also started to make the app-routing into more of a hierarchy, with :entity/:space as a parent componentless route, which we should do anyway, as it will make the routing easier to reason about.

**Comment by pmuir** [comment]
You have to directly enter http://localhost:3000/rhn-support-pmuir/BalloonPopGame/plan;view=board in your nav bar to use it, I didn't update any links.

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-559-fabric8-ui.int.rdu2c.fabric8.io

**Pull request closed without merging**
