### PR TITLE
fix(logging): remove logging

### PR DESCRIPTION
**Pull request by jstrachan**
its a bit noisy

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1109-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
If it is a bit noisy, that tells me there is a memory leak we should fix instead of ignore by removing the logging.

**Comment by jstrachan** [comment]
Neither log statements add any actual value - they are old debugging statements.

plus when a pipeline is pending/building/waiting approval you get 4 lines per second which makes the JavaScript console pretty hard to use. 

I can imagine it using up a fair bit of memory too - as it forces the browser to keep around at least a copy of every full BuildConfig object tree for every second!

**Pull request merged**
