### PR TITLE
Restores files removed by previous commit for EE tests

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4af3b7b31ff2073205079499cd0f63a2ad067d2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters

 * Commit: 04d93a21f1cc1357eed4926fea8b891b9932f3f0
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-702.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e876f19fc7b19628098c6c17aeb47e1f67f98c3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters

 * Commit: 9b9e6b3fe91f2bbe577878c84cb0be8a62e4cad4
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: baa01d5954457714c0ccde17ad59b13b8a0becf3
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by ldimaggi** [comment]
[test]

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-702.int.rdu2c.fabric8.io

**Comment by kbsingh** [comment]
for the test part, this looks good to me.

**Pull request merged**
