### PR TITLE
feat(apps page): adds the Apps page

### PR DESCRIPTION
**Pull request by jstrachan**
lets add back the environments page now it seems to be working again

### CODE REVIEW

**Comment by jstrachan** [comment]
**NOTE** lets not merge this until after the demos next week!

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1203-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@jstrachan this looks like it was merged with a different PR, closing this. Please reopen it if it is still needed.

**Pull request closed without merging**
