### PR TITLE
Update package.json ngx-login-client to 0.4.4

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0b4e743d62e7b6693c51b4182e5427c81e4ddcf3
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by rawlingsj** [comment]
automatically generated by a pipeline, closing to avoid merge as fabric8-ui requires updates to work with ngx-login-client 0.4.4

**Comment by rawlingsj** [comment]
@joshuawilson I just took a quick look at that update function and it now avoids the package.json formatting issues.

This was the commit it generated - it looks better :)
https://github.com/fabric8io/fabric8-ui/pull/254/commits/0b4e743d62e7b6693c51b4182e5427c81e4ddcf3

**Comment by joshuawilson** [comment]
That is much better, thanks

**Pull request closed without merging**
