### PR TITLE
feat(supportloginchanges): Adds support for updated login client

### PR DESCRIPTION
**Pull request by dgutride**
Login client no longer is responsible for routing
so application routing logic moved into the application 
handling the token if it's loaded on the url after
the user has been authenticated

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4ba6af7c21be86f7753ae4abe7a77b0d97bf3d97
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a8bdbb152a1066e66efcc875acb6df59e6c719cd
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
DO NOT MERGE until the same fix is applied to planner.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eed6c99703c0253b8f4653d827b45c54a943356
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5eed6c99703c0253b8f4653d827b45c54a943356
  * Your subject line is longer than 50 characters

 * Commit: 64a30e343196b7503413804db987ecd14cdff847
  * Your commit message does not contain a body
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fe2342b22c75ce4f9df8b89685faedb844cc3c71
  * Your subject line is longer than 50 characters

 * Commit: 865a6eb4e94b7fc62bfb8ef91300354e497de9f6
  * Your commit message does not contain a body
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 16a42b94003e31950b69dc32e21fedfbc55746ce
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4eebf9a26e9139df46c911b4ca61c6feef27c329
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4eebf9a26e9139df46c911b4ca61c6feef27c329
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
