### PR TITLE
fix(tests): Add page object model for URL tests

### PR DESCRIPTION
**Pull request by naina-verma**
This PR contains Page object model for URL tests

### CODE REVIEW

**Comment by naina-verma** [comment]
@ldimaggi can you please review this !

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1304-fabric8-ui.int.rdu2c.fabric8.io

**Comment by naina-verma** [comment]
[test]

**Comment by sbose78** [comment]
[test]

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1304-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
