### PR TITLE
fix(codebases): Updated to reflect latest mockups

### PR DESCRIPTION
**Pull request by dlabrecq**
- Added open workspace button.
- Modified kebab options to create a workspace.
- Added default workspace selection to menu using the new last_used_workspace property from /api/spaces/x/codebases API.
- Added create workspace link when no workspaces are available.
- Added busy indicator when workspace is created and/or opened.
- Added info icon and tooltip in workspaces column header.
- Added timer to poll for new workspaces in order to set the workspace selection menu. 

First timer interval is 3 sec, then every 30 sec for 5 min or a new workspace is found.

Reviewed with @catrobson 

screen shot 2017-04-26 at 8 15 34 pm

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1126-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by catrobson** [comment]
@dlabrecq - when I hover on the info tip, the first row is highlighting:
image

Otherwise things look really good!

**Comment by dlabrecq** [comment]
Thanks. I'll look at the row highlight separately.

**Pull request merged**
