### PR TITLE
fix(space-wizard): fix default demo github failure dependency

### PR DESCRIPTION
**Pull request by mitchharpur**
-the specified repo is now propagated through the wizard
- added spinners between  steps due to higher latency caused by more server side validation
- all fields are now sent to forge service on each step

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51aa5e4203f6c02e2a802f9e2f212e34ddceb80a
  * Your subject line is longer than 50 characters

 * Commit: 10ed36973c85b8348760f4b8de01de62e620bbed
  * Your subject line is longer than 50 characters

 * Commit: 3db8c2535d6e85b98baaea3d7dfbad00a2a3e21b
  * Your subject line is longer than 50 characters

 * Commit: 3d6db1a271c558f714a5126f3ad3e670e9ba626a
  * Your subject line is longer than 50 characters

 * Commit: 03bcadbcb8764e2419588b55f44b2cdf0b7ee490
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1119-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 51aa5e4203f6c02e2a802f9e2f212e34ddceb80a
  * Your subject line is longer than 50 characters

 * Commit: 10ed36973c85b8348760f4b8de01de62e620bbed
  * Your subject line is longer than 50 characters

 * Commit: 3db8c2535d6e85b98baaea3d7dfbad00a2a3e21b
  * Your subject line is longer than 50 characters

 * Commit: 3d6db1a271c558f714a5126f3ad3e670e9ba626a
  * Your subject line is longer than 50 characters

 * Commit: 03bcadbcb8764e2419588b55f44b2cdf0b7ee490
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6aaf12ec6bd26920e75385219c449212f90a4da7
  * Your subject line is longer than 50 characters

 * Commit: 51170b91628a471e25b6d8d1f43a95baae61c7bc
  * Your subject line is longer than 50 characters

 * Commit: d16e2bdb9a1c5091965f16bf85a3c9f69d1867ce
  * Your subject line is longer than 50 characters

 * Commit: 65e64e54d88c19f2cfa101fefcf397dcff6ffb6e
  * Your subject line is longer than 50 characters

 * Commit: 7e3af76bece22e542011854395e80f5a840fa4cd
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1119-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
