### PR TITLE
fix(space-wizard): correct some ux styles and add some validation

### PR DESCRIPTION
**Pull request by mitchharpur**
- brings commits forward from prior pr (correct progress indicators and better error handling)
- add some validation for wizard controls
- fixes to forge page styles based on ux feedback
- fixes to wizard page styles from ux designs
- fix move to next step not working correctly when initial validation fails

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7639c931b6390db854f2822de4499f993ced9fbc
  * Your subject line is longer than 50 characters

 * Commit: e09c1a1cdb779b8e52cdc9346a07a8de46ebd541
  * Your subject line is longer than 50 characters

 * Commit: 94f3b2297f6a6a0d05885a6005adae41e97b8067
  * Your subject line is longer than 50 characters

 * Commit: da1ebfc82d6759dd70039fa6f6d9b74c339989fa
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1018-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1018-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
@mitchharpur closing this as it appears the work is in #1026

**Pull request closed without merging**
