### PR TITLE
Planner fix

### PR DESCRIPTION
**Pull request by sanbornsen**
**DO NOT MERGE**
**DO NOT CLOSE EITHER**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 84dc825678170c7c8a0ee4360a40419993dd9f74
  * Your commit message does not contain a body

 * Commit: ee19ebe22e429618d77984bf6ca860d5aae425e8
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 84dc825678170c7c8a0ee4360a40419993dd9f74
  * Your commit message does not contain a body

 * Commit: ee19ebe22e429618d77984bf6ca860d5aae425e8
  * Your commit message does not contain a body

 * Commit: d8aa31511172ad2817636cdd445bc5d358254669
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 84dc825678170c7c8a0ee4360a40419993dd9f74
  * Your commit message does not contain a body

 * Commit: ee19ebe22e429618d77984bf6ca860d5aae425e8
  * Your commit message does not contain a body

 * Commit: d8aa31511172ad2817636cdd445bc5d358254669
  * Your commit message does not contain a body

 * Commit: da6917bde819b01ea46b3cee34eecc930a1117be
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
DO NOT MERGE

**Comment by pmuir** [comment]
@sanbornsen do we still need this?

**Comment by joshuawilson** [comment]
it looks like the fixes in the Planner have fixed what this was supposed to fix, I'm guessing we don't need it.

**Comment by joshuawilson** [comment]
@sanbornsen Can we close this?

**Comment by sanbornsen** [comment]
IIt's not a fix, it's a way of integrating planner inside platform and I  think this is the correct way of doing that. Please go through the PR once.

**Pull request merged**
