### PR TITLE
fix(runtime env vars): lets load env vars

### PR DESCRIPTION
**Pull request by jstrachan**
lets try another approach to #1316 by loading eagerly a blob of JSON on startup so that the env vars can be injected without blocking via @Inject which simplifies the code changes to all the fabric8-ui modules

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1401-fabric8-ui.int.rdu2c.fabric8.io

**Comment by pmuir** [comment]
+1 to this basic approach, but I didn't do a detailed review.

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1401-fabric8-ui.int.rdu2c.fabric8.io

**Comment by jstrachan** [comment]
@pmuir @joshuawilson fancy having a look at this PR - its seeming to work way better than the previous approach. 

The main issue is to work with all the gazillions of `@Inject(FOO_API_URL) someUrl: string` code thats littered throughout our codebases in this repo, `ngx-login-controller` and `fabric8-runtime-console` we can't have lazy loading of the `Fabric8UIConfig` object; so instead I load a [fabric8-ui.env.js](https://github.com/jstrachan/fabric8-ui/blob/43a097c635f5d161ca0990d1d9ea75c44a818b8d/src/config/fabric8-ui.env.js) file early in the [index.html](https://github.com/jstrachan/fabric8-ui/blob/43a097c635f5d161ca0990d1d9ea75c44a818b8d/src/index.ejs#L15) so that we can implement a simple synchronous provider of `Fabric8UIConfig` via [this code](https://github.com/fabric8io/fabric8-ui/pull/1401/commits/43a097c635f5d161ca0990d1d9ea75c44a818b8d#diff-9e0521b941b38a0a9cdfa15f55bc7034R24)

if you're happy with this approach (which on balance seems the simplest thing that could possibly work and avoids the startup timing issues of async loading of injected static strings), I can re-implement the `Observable<Fabric8UIConfig>` using the same underlying provider and remove the `fabric8-ui.config.json` file which is no longer required

**Comment by fabric8cd** [comment]
@jstrachan snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1401-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
I'm going to merge this, the issues can be fixed in another commit

**Pull request merged**
