### PR TITLE
fix: OpenShift case in visible text

### PR DESCRIPTION
**Pull request by qodfathr**
Resolving issue #354

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 27499e790a49353eebe5bdb55803709bd936b71d
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 27499e790a49353eebe5bdb55803709bd936b71d
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
@qodfathr you may have done this through the webui, in which case it it is not possible, but in general we ask that you run `git rebase origin/master` (assuming origin is this repo, and you have another remote called e.g. qodfathr to push your changes to).

**Comment by pmuir** [comment]
[test]

**Comment by qodfathr** [comment]
@pmuir  I missed the rebase -- my bad. I forked from here to qodfathr, then I made a new branch, did my work on that new branch, did a PR from that branch to my master, and then a PR from my master to here. I see that I took the long, windy road.

**Comment by pmuir** [comment]
Luckily github provides a rebase and merge option nowadays ;-)

**Pull request merged**
