### PR TITLE
Emissions

### PR DESCRIPTION
**Pull request by pmuir**
/cc @jstrachan adding the distinctUntilChanged on each store did help a bit, as did doing a zip. I'm not 100% sure, but I think that might be it?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ed2aa47cf9c2c749f679f1d97459a47a06310ada
  * Your commit message does not contain a body

 * Commit: 8de97f0ac6c0714f23b3ff2598b9b032f8c478ef
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
@jstrachan what I couldn't work out what was what uniquely identifies the build and build config objects we get from openshift - with this I might be able to better filter the streams. I'm going to dig a bit deeper tomorrow.

**Comment by pmuir** [comment]
Not sure the zip is correct though.

**Comment by pmuir** [comment]
[test]

**Pull request closed without merging**
