### PR TITLE
fix(analytic-dash-widget): load fix

### PR DESCRIPTION
**Pull request by jyasveer**
1. dashboard is now loading with the latest valid pipeline
2. added the message for no recommendations

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jyasveer snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1513-fabric8-ui.int.rdu2c.fabric8.io

**Comment by jyasveer** [comment]
could anyone please review this

**Comment by fabric8cd** [comment]
@jyasveer snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1513-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
