### PR TITLE
fix(router): Sticking to iteration filter on view change in planner

### PR DESCRIPTION
**Pull request by sanbornsen**
ISSUE : https://github.com/fabric8io/fabric8-planner/issues/1712

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e77452d97eca6570d9a04fd2f7ad2f9a9de6d2dd
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-961-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4f45cbff01615a23e6489303887babfdb3948d6
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-961-fabric8-ui.int.rdu2c.fabric8.io

**Comment by catrobson** [comment]
@sanbornsen I'm seeing an issue where multiple items in the left hand panel are showing as selected in the snapshot:
image

**Comment by joshuawilson** [comment]
Please fix it so that the encoded slashes are not in the URL.

**Pull request merged**
