### PR TITLE
Add resource requests/limits

### PR DESCRIPTION
**Pull request by vpavlin**
Please, let me know if you don't think these limits are reasonable.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 47a7f38dae8d33bff75f660151cf8f6f18d30406
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-951-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
I'm not sure how I would know what is reasonable on this. @pmuir do you know?

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
