### PR TITLE
fix (test): update EE test to run on production openshift.io

### PR DESCRIPTION
**Pull request by ldimaggi**
This PR can wait until May 5 - thx!

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04e165b6d30f7182c3eb2193243a416db68b2a8d
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04e165b6d30f7182c3eb2193243a416db68b2a8d
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: eef2c9ec64f54a66b94b24d0eed5326136bf6cb4
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 557c651380c7d74d7aefbb1991c3804135bb0b48
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 332e8b9850f925aa7b2e3cb7f25434b4946f758f
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: dc5b49beec862192df9528252897e823d85a6843
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8dcb6f02c94be0e554ff8b881ef357e0a06f6fad
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ec7ec44dd4ea7f87129953efaa7b21d143d140a7
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 31aa43562de0dca5a5bb32108758ec7c6924434f
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 634a46d79cf42aded0d28f58ce848f22b42bad0e
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8dcb6f02c94be0e554ff8b881ef357e0a06f6fad
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ec7ec44dd4ea7f87129953efaa7b21d143d140a7
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 31aa43562de0dca5a5bb32108758ec7c6924434f
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 634a46d79cf42aded0d28f58ce848f22b42bad0e
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ab81f705a6224a34d59bf970a868aa49059161b3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04d73b6286f64d327ee4832cb7081f42f6fb7cae
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b3ef69e176ed77b3e485456226d4c3fb518ddf01
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 9837d7a4992b9a3971daddb9a02e3afaff57027a
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 32f16c97890fb70779a63b784051c4e65c4da3d2
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a0f940d48cde6f4b526954a6a921a10d3bdfcd8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 4119cf7c38dc19d135011849782d8bee50df74ef
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04d73b6286f64d327ee4832cb7081f42f6fb7cae
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b3ef69e176ed77b3e485456226d4c3fb518ddf01
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 9837d7a4992b9a3971daddb9a02e3afaff57027a
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 32f16c97890fb70779a63b784051c4e65c4da3d2
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a0f940d48cde6f4b526954a6a921a10d3bdfcd8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 4119cf7c38dc19d135011849782d8bee50df74ef
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 1a9c0607f27331824e391b6140bca2d803cbdfcb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04d73b6286f64d327ee4832cb7081f42f6fb7cae
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b3ef69e176ed77b3e485456226d4c3fb518ddf01
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 9837d7a4992b9a3971daddb9a02e3afaff57027a
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 32f16c97890fb70779a63b784051c4e65c4da3d2
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a0f940d48cde6f4b526954a6a921a10d3bdfcd8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 4119cf7c38dc19d135011849782d8bee50df74ef
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 1a9c0607f27331824e391b6140bca2d803cbdfcb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 6bda5a4f55ae547436892e69b5111c4c9a0bd0fe
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 04d73b6286f64d327ee4832cb7081f42f6fb7cae
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b3ef69e176ed77b3e485456226d4c3fb518ddf01
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 9837d7a4992b9a3971daddb9a02e3afaff57027a
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 32f16c97890fb70779a63b784051c4e65c4da3d2
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a0f940d48cde6f4b526954a6a921a10d3bdfcd8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 4119cf7c38dc19d135011849782d8bee50df74ef
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 1a9c0607f27331824e391b6140bca2d803cbdfcb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 6bda5a4f55ae547436892e69b5111c4c9a0bd0fe
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 4c015c620a6131e1893788374fd49dae4302a21e
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6a8b30679ae8a8fa67792c19f7d9c941264e58d9
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b0881235f7932a23c790d5b07187c366d0e62f78
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 467386f5dd6824a98d4060d82ab804a475fc0765
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 1814e27dd9d3465a808faaa66ea433edf5a947e7
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 7d1ba0efb4e5e98925a917b6bc2ba157656d4b96
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 27b98de46b841a8a4b9f4472b20954d2b6a97cf0
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 75039d83b26ce1a2ce6400c992843e03e18724b9
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 8538e058a1d7798263635d5692de76db240b6a14
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 84f8b56400144ba61d6dfe6ae95d7a10bcba6cdf
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 854bbf0585815b3d0469f8f6b551b1438341cac9
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: ec4b55e4bd051ff9421c34f8f6b77731a0107a2f
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 853ad465bb51b821f508b376ea1f54125add67c7
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 8d241c12ad0c73856e9297c23e2d33a1006bf4df
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 931adda445a85e55c211e4f95f822700ec23fe37
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: cc28a0714e1321470fccde1a6b5948213ae06277
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 5a51476929285699fa495ac7dec741275e376507
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 743afb0d1fbdfd977ab606e2dd92ade64f4a9b9a
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 516cf235467820175e2b777c75ee14969dcb2aab
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 04298329c96abda02541f366cb7badb19d2ec467
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
There is no space in the commit message between "fix" and "(test)" it should be "fix(test): add another test case".

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1648941abd53336fda66dc6264cda1e4d70098da
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: e157ef447815b7b01b33a6c2d247706665b491fc
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 5480b98833987d9e3d4e31eddac67eca20a220cd
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 561008c44b0fdaf0aeab811d9f09eaff83ccb746
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 2801de2f6e3f12a599704cffbcf88b297297d16c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 605ea801cd1e3d235aa21e358f332e34c0b2d926
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: f98241b78ee73561fe9757d23caad6ab7b9f852b
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: b3b44189bc7775aed0a6bd65c8e1fac097965d06
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a364689cafdfcd8ffcb54bdc156143bfac318910
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a5f185c3c9337ddd787a172a65c2f0a88a0b0e52
  * Your subject line is longer than 50 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: a46bb088c4ace5021c1434e1e77be84a61c9aa3b
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1218-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
