### PR TITLE
chore(rename.env.variable): prefix with FABRIC8 to match convention"

### PR DESCRIPTION
**Pull request by corinnekrych**
@xcoulon as discussed rename variable to FABRIC8_REALM.
I've aslo rename it in planner in: https://github.com/fabric8io/fabric8-planner/pull/1913/commits/039401db666c5214a2844660030aabda19437515

Is it ok to merge?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 92a53462c78e415ca73668e7f97b0010ae95317d
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1376-fabric8-ui.int.rdu2c.fabric8.io

**Comment by sbose78** [comment]
Checked prod and prod-preview deployments, we don't use any env variable to set the realm.
We allow the defaults to be used - so this PR being merged shouldn't impact anything when elevated all the way to production.

**Comment by joshuawilson** [comment]
Don't forget to update the Stack Recommender as they added the Realm too.
https://github.com/fabric8-ui/fabric8-recommender/pull/214

**Comment by corinnekrych** [comment]
@joshuawilson I've rename it it there too https://github.com/fabric8-ui/fabric8-recommender/pull/216 
Although keeping old name won't make the build/runtime fails but agreed, to align naming is better.
cc @xcoulon

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 92a53462c78e415ca73668e7f97b0010ae95317d
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1376-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
