### PR TITLE
fix: add x-request-id to all http requests

### LINKED ISSUE #348: UI should generate a unique ID for all http requests
Using the HTTP Header **X-Request-Id**

ID is used to track requests from client to backend services.

### PR DESCRIPTION
**Pull request by pmuir**
* Uses uuidv4 to genreate a unique id per request

Fixes #348

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: affde6d937bcdf7f9ee0ad4391673289a1444331
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
when I run this locally I get a 400 Bad request

I refresh, hit the blue login button (sometimes twice), get 400

**Comment by pmuir** [comment]
I will need the entire console and network logs (please set preserve log to true).

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: affde6d937bcdf7f9ee0ad4391673289a1444331
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ed21fb68a2ef8e69ea63165f6c136ba1afa53d93
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
Added another commit which should help resolve that I think.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c38ef3257b783fc17f9e0cabf0f70e098055ac3b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8e9ff7f27ee5816ecfe71a0b8fd0f7416218c6fe
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
