### PR TITLE
Update package.json ngx-login-client to 0.4.4

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 60b587188274021dec66b388425efee240c91e33
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
@rawlingsj the commit looks good but we are not ready to accept that upgrade. Is this a test or did you turn on the system?

**Comment by rawlingsj** [comment]
@joshuawilson this was an automated PR as a result of a ngx-login-client release earlier this evening by the looks of things however that was 0.5.0 so this PR looks incorrect.  

As I increase the automation over the next few working days we're likely to see a bit of noise but I'll try my best to make any PR or interactions informative to others.

**Comment by joshuawilson** [comment]
@rawlingsj I think it is great.

But it does need to use the latest. :)

**Pull request closed without merging**
