### PR TITLE
fix(providerService): Decode tokens using UTF-8

### PR DESCRIPTION
**Pull request by dlabrecq**
Added the jwt-decode package to ensure auth token is decoded with UTF-8 support.

Fixes: https://github.com/fabric8io/fabric8-ui/issues/1285

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1300-fabric8-ui.int.rdu2c.fabric8.io

**Comment by ppitonak** [comment]
@dlabrecq I cannot login on https://fabric8-ui-fabric8-ui-pr-1300-fabric8-ui.int.rdu2c.fabric8.io

**Comment by dlabrecq** [comment]
The snapshot appears to use a prod-preview environment. Perhaps you're authorized for prod only?

**Comment by ppitonak** [comment]
@dlabrecq I managed to open the link and link my Github account but I'm not 100% sure that my name in my account is still set to the same string (with Slovak characters)

**Comment by alexeykazakov** [comment]
@ppitonak your profile doesn't have any Slovak characters anymore. I updated it before the issue was fixed.

**Comment by ppitonak** [comment]
@alexeykazakov is there a way for me to re-set it to contain Slovak characters again? I also probably need to unlink my Github account to verify this PR.

**Comment by alexeykazakov** [comment]
@ppitonak see PM in Mattermost

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1300-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
