### PR TITLE
Add ConfigMap

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 780dea66161ab150feb0fcf7c4e2437895f54f74
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@vpavlin snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-741-fabric8-ui.int.rdu2c.fabric8.io

**Comment by kbsingh** [comment]
[test]

**Comment by kbsingh** [comment]
lgtm

**Pull request merged**
