### PR TITLE
feat(home): Added work item widget to home page

### PR DESCRIPTION
**Pull request by dlabrecq**
This work item component displays work items assigned to the user.
The select menu allows the user to select from the latest 10 spaces.
By default, the component will select a recent space which is populated with work items.
Reviewed with Catherine.

screen shot 2017-04-20 at 11 48 52 am

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@dlabrecq when I tried out the snapshot, the dropdown is blank until I select something - is there a way to have the placeholder show up without opening the dropdown?
screen shot 2017-04-20 at 2 50 28 pm

**Comment by joshuawilson** [comment]
It doesn't really work for me. when I refresh on the home screen and I have a space select it doesn't show anything, but if I go to the space (I also went to the planner) and then go back to home it displays.

**Comment by joshuawilson** [comment]
If it doesn't already do so, it should default to the most recent space.

**Comment by joshuawilson** [comment]
@catrobson regarding the design of this, I was thinking it would show me my most recent issue regardless of the space. Github does this on my home page.

**Comment by dlabrecq** [comment]
It won't show anything unless you assign yourself to a work item. If there were no work items in a recent space, it won't populate automatically. You would have to select a space yourself.

I have also encountered the scenario where the most recent spaces are not obtained. However, I believe that is searate bug.

You can verify that your recent spaces are not showing up in the menu at the top.

**Comment by dlabrecq** [comment]
It defaults to the most recent space that has work items assigned to the user.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aef89422803f63d98c5e0752e35b6b0a53675b8c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by dlabrecq** [comment]
@joshuawilson Please try again. 

I coded things a bit differently to ensure a menu option is not selected until a (recent) space has been found with assigned work items.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by dlabrecq** [comment]
In order to resolve work items, Planner's workItemService.resolveAreaForWorkItem and workItemService.resolveCreator are called. In turn, AreaService.getAreas is called.

Instead of returning an empty Observable, AreaService was recently changed to throw an exception when an area is not found. Planner's code then breaks when calling workItemService.resolveCreator because workItem.relationalData remains undefined.

My local repo didn't have this new change, unlike the generated snapshot. To resolve the issue, I must capture the thrown exception.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-941-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
