### PR TITLE
chore(space-wizard): refactor forge client

### PR DESCRIPTION
**Pull request by mitchharpur**
- refactors forge service client to have correct dependency injection non singleton semantics and is now injected into component instead of being explicitly instantiated.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca7a5ea83249f15f747958326e23a87dffceada9
  * Your subject line is longer than 50 characters

 * Commit: 72c645f0cc140742583f83ece2054bb75e43a8fb
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca7a5ea83249f15f747958326e23a87dffceada9
  * Your subject line is longer than 50 characters

 * Commit: 72c645f0cc140742583f83ece2054bb75e43a8fb
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1404-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1404-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 03a441ce3bb257625339a3544dff4838be96ceb1
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1404-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
