### PR TITLE
feat(space-wizard): improved error handling and progress indicators

### PR DESCRIPTION
**Pull request by mitchharpur**
feat(space-wizard): improved error handling and progress indicators

- added better error formatting to make it easier to know what went wrong .. especially for server side partial completions involving security failures
- added ux pf spinners as followup to ux feedback

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 038168c3ee3d38f691f51bf3be08aa04b02604c8
  * Your subject line is longer than 50 characters

 * Commit: a876dd0b6e12e234b2b28d2eecc9ff02b1f598b0
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-995-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-995-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
@mitchharpur when I use the snapshot link to test it out, I can't get past the Next button. It just resets the first page of the form. The Finish button works.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0bb9471ecf992ef40de33d8b7845d272204ba3ec
  * Your subject line is longer than 50 characters

 * Commit: 067fd60d9576e9b8afd49bb0bfb55d62dfc2dfcf
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-995-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 10f8c1f8542f6abaded2f7921eb59361d9765e5c
  * Your subject line is longer than 50 characters

 * Commit: 05860ef6a71da25b3c99e243ab5d0f8669da1e84
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-995-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b9a297f946bf2e0af4affbab19001978727ba8f6
  * Your subject line is longer than 50 characters

 * Commit: 14b1d7602f93ef01b7e62df0bd9fe62aa79424b1
  * Your subject line is longer than 50 characters

 * Commit: 38c7d2518c5761905cd466b24519032463906ccc
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-995-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by mitchharpur** [comment]
replicated in next pr

**Pull request closed without merging**
