### PR TITLE
chore(build): make sourcemaps for deps work

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by joshuawilson** [comment]
rebase and if you have time fix to include only the libs we created

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d0db4ab9473158fb7d325cc4e841989eef4918fc
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
Rebased.

**Comment by pmuir** [comment]
[test]

**Pull request merged**
