### PR TITLE
set the home spaces list to show recently visited spaces

### PR DESCRIPTION
**Pull request by joshuawilson**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b45cdb60e4b2d17f168f4799a116a3342626bef4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-914-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b45cdb60e4b2d17f168f4799a116a3342626bef4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-914-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
