### PR TITLE
fix(space-wizard): improve ux as per design, remove tech debt and fix some defects  

### LINKED ISSUE #885: Add the codebase Git repo
Auto add the codebase Git repo to codebases when you complete the wizard for create space

### LINKED ISSUE #1043: quickstart wizard should render the pipeline choices using a visual pipeline representation
rather than just a list of pipeline names it'd be nice to show a list of pipeline renderings for each pipeline choice.

The JSON returned by the wizard has the stages, environments and a description.

e.g.
```json
    "inputs":
    [
        {
            "name":"pipeline",
            "shortName":" ",
            "valueType":"io.fabric8.forge.generator.pipeline.PipelineDTO",
            "inputType":"org.jboss.forge.inputType.DEFAULT",
            "enabled":true,
            "required":false,
            "deprecated":false,
            "label":"Pipeline",
            "description":"The Jenkinsfile used to define the Continous Delivery pipeline",
            "valueChoices":
            [
                {
                    "id":"Release",
                    "builder":"maven",
                    "descriptionMarkdown":"Maven based pipeline which:\n\n* creates a new version then builds and deploys the project into the maven repository\n* runs an integration test in the **Test** environment\n* stages the new version into the **Stage** environment\n",
                    "environments":
                    [
                        "Test"
                    ],
                    "label":"Release",
                    "stages":
                    [
                        "Build Release",
                        "Integration Test"
                    ],
                    "value":"maven/Release/Jenkinsfile"
                },
                {
                    "id":"ReleaseAndStage",
                    "builder":"maven",
                    "descriptionMarkdown":"Maven based pipeline which:\n\n* creates a new version then builds and deploys the project into the maven repository\n* runs an integration test in the **Test** environment\n* stages the new version into the **Stage** environment\n",
                    "environments":
                    [
                        "Test",
                        "Stage"
                    ],
                    "label":"ReleaseAndStage",
                    "stages":
                    [
                        "Build Release",
                        "Integration Test",
                        "Rollout to Stage"
                    ],
                    "value":"maven/ReleaseAndStage/Jenkinsfile"
                },
                {
                    "id":"ReleaseStageApproveAndPromote",
                    "builder":"maven",
                    "descriptionMarkdown":"Maven based pipeline which:\n\n* creates a new version then builds and deploys the project into the maven repository\n* runs an integration test in the **Test** environment\n* stages the new version into the **Stage** environment\n* waits for **Approval** to promote \n* promotes to the **Run** environment\n",
                    "environments":
                    [
                        "Test",
                        "Stage",
                        "Run"
                    ],
                    "label":"ReleaseStageApproveAndPromote",
                    "stages":
                    [
                        "Build Release",
                        "Integration Test",
                        "Rollout to Stage",
                        "Approve",
                        "Rollout to Run"
                    ],
                    "value":"maven/ReleaseStageApproveAndPromote/Jenkinsfile"
                }
            ],
            "class":"UISelectOne",
            "value":"ReleaseStageApproveAndPromote"
        }
    ]
```

For example the `ReleaseStageApproveAndPromote` pipeline choice has stages:

* Build Release
* Integration Test
* Rollout to Stage
* Approve
* Rollout to Run

To render that like the pipelines UI it should be fairly easy - something along these lines

```html
<div class="pipeline">
  <div class="pipeline-stage" **ngFor="let stage of stages">
    <div class="pipeline-stage-column">
      <div class="pipeline-stage-name Cancelled" title="stage status: SUCCESS">{{stage}}</div>
        <div class="pipeline-status-bar SUCCESS">
          <div class="pipeline-line"></div>
          <div class="pipeline-circle">
            <div class="clip1"></div>
            <div class="clip2"></div>
            <div class="inner-circle">
              <div class="inner-circle-fill"></div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
```

then we'd just need similar CSS loaded like is used in the fabric8-runtime-console's pipeline rendering:
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.scss

(we could omit a fair bit of that CSS as we'd only show SUCCESS states and would not show animations)

### LINKED ISSUE #1071: In 'Add to space" the "Next" button fails
Steps to recreate - on https://prod-preview.io

* Create a new space, or navigate to an existing space
* Select "Add to space"
* Select "Technology stack and pipeline"
* Select Vert.X CRUD (or other Vert.X options)
* Click on "Next" button - and the "Add to space" dialog is refreshed

The workaround is to click on the "Finish" button.

Console log - no error is logged:
```

ForgeAppGenerator 5 Validation request for command forge-quick-start:validate:0.
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Validation request for command forge-quick-start:validate:0.
main.cdb387e….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator executing the 'forge-quick-start :: validate :: 0' command ...
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8ForgeService 2 Forge POST request  : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/validate
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8ForgeService 2 Forge POST response : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/validate
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator 'forge-quick-start :: validate :: 0' command completed
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Validation response for command forge-quick-start:validate:0.
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Next request for command forge-quick-start :: next :: 1.
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Next request for command forge-quick-start :: next :: 1.
main.cdb387e….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator executing the 'forge-quick-start :: next :: 1' command ...
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8ForgeService 2 Forge POST request  : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/next
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8ForgeService 2 Forge POST response : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project/next
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator 'forge-quick-start :: next :: 1' command completed
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Next response for command forge-quick-start :: next :: 1.
main.cdb387e….bundle.js:1 Object
main.cdb387e….bundle.js:1 ForgeAppGenerator 5 Stored fieldset[4] into fieldset history
                  ... there are 1 responses in history ...

```

### LINKED ISSUE #1208: Screen display is corrupted when creating new space project in Firefox on Windows
Firefox screenshot:

screenshot 2

In contrast - here's the same operation in Chrome:

screenshot 3

### PR DESCRIPTION
**Pull request by mitchharpur**
Closes #1043 
Closes #885
Closes #1208 
Closes #1071

* ux improvements
==============
- improve responsive behavior of wizard with edge,firefox,safari and chrome
- resolve white space overflow issue causing  dialog to appear malformed when page resized
- bring ux in closer conformance with ux design.
- add wizard step visualizer ( i.e show current step indicator on top of forge form)
- add wizard pipeline visualizer (i.e show pipelines stages/description as returned from forge) 

* feature fixes
===========
- add visualizers per ux designs
- add codebase to space and close wizard dialog after used acknowledges result

* tech debt improvements with a view to moving to an npm module
=================================================
- better encapsulate styles and style cleanup /refactoring
- clean up and linting
- refactor dialog close logic
- improve error handling
- prep for moving to npm module
- added optional console log formatting

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d4538b5e4af59801a9bb2eb78194364122effa6b
  * Your subject line is longer than 50 characters

 * Commit: b4e02425bda74fdfd48634d595b0b2edadb0e0cf
  * Your subject line is longer than 50 characters

 * Commit: 44a3011ab92d45d38bdcc87fc96c8e879b0227c3
  * Your subject line is longer than 50 characters

 * Commit: a4e98b881fc9dc299661bd5bdb538c3f6ef8ea9c
  * Your subject line is longer than 50 characters

 * Commit: 3e809104e71f6bf502e792157de583bfb6aa3f69
  * Your subject line is longer than 50 characters

 * Commit: 369cebc3c403f9350bf5c827421b7356a8729701
  * Your subject line is longer than 50 characters

 * Commit: b0204a2b3b00ec97d908d08f463a8afe54f9e4ff
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5326a6a560f6ea1e0b71473c4a40031196524a7c
  * Your subject line is longer than 50 characters

 * Commit: 5e9df857b7185b21661fca6e2342e03f18701b35
  * Your subject line is longer than 50 characters

 * Commit: b4c5a075b432d0600489412eb1a0603b6b647a40
  * Your subject line is longer than 50 characters

 * Commit: 069bc31cd82352676ef45e77878a2992fe694b75
  * Your subject line is longer than 50 characters

 * Commit: 13cd9cb143dcab74e157a09afe9014b250226235
  * Your subject line is longer than 50 characters

 * Commit: 86587e38ff8c2b9db901feec09816e02a904e788
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters

 * Commit: 725d05e9977d9ab47d784a74ffd0147fe1c07942
  * Your subject line is longer than 50 characters

 * Commit: b14616dee67c1c76fe42b273e553ff46b1b1aeb5
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1309-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
Please rebase.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d2100e6150f041a2b8d9af8bf59fe4e35dbf2228
  * Your subject line is longer than 50 characters

 * Commit: 2a34c3ff7f2ddf5d72f844a7efab32ec555cefeb
  * Your subject line is longer than 50 characters

 * Commit: 631ef33b44b47a795c8ad62e9baa18d9732b4484
  * Your subject line is longer than 50 characters

 * Commit: 6d9755b1e28b2615a7228ea47ef70899aaac9703
  * Your subject line is longer than 50 characters

 * Commit: 118b6bb03f0457bce33636d3390aadddc985543c
  * Your subject line is longer than 50 characters

 * Commit: 5fad7f9fd2bbf20396b1b256f9103d1fb7e04f51
  * Your subject line is longer than 50 characters

 * Commit: 356808ab2ae4e490da704fd4c62922b2f3b8d018
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4db9e0b3d0b03babaa90bb8006c9f783aeb21cae
  * Your subject line is longer than 50 characters

 * Commit: 5b120cfdfb9e84a08a1737c7dbe715eac2393864
  * Your subject line is longer than 50 characters

 * Commit: d05eba512d7f155f5ade116f73ed3972f174467e
  * Your subject line is longer than 50 characters

 * Commit: 5708310c6b75be9441d4dd28d0bbe99beed31e77
  * Your subject line is longer than 50 characters

 * Commit: 948cf26f18293f8240422084a03a6eeef993df3c
  * Your subject line is longer than 50 characters

 * Commit: ae0bf0dd8320c2668433eacb7cadcfb677385e83
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters

 * Commit: 1303eb81b864e800c46065859f05db1f0d4e25d4
  * Your subject line is longer than 50 characters

 * Commit: 90367c310e1bdf210b5b0d4f218ce98f401e8a86
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1309-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
