### PR TITLE
chore(space-wizard): tech debt removal and fixes

### PR DESCRIPTION
**Pull request by mitchharpur**
- add notification on successful codebase add to space
- tech debt removal : more refactoring into smaller components
- fix forge panel navigate to space

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4477bb0042241dbb73db97aac91400338dcb7630
  * Your subject line is longer than 50 characters

 * Commit: a72111691bfca5677a7d6696a94e03f5134e9eed
  * Your subject line is longer than 50 characters

 * Commit: 155754dfc8fdb27a6cf5dcf71abc4c9e079e85aa
  * Your subject line is longer than 50 characters

 * Commit: 27b89775594947577332a271258fdd603eef6bfa
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1400-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2abcdc3860d1807eb854c3229ff81e1629717ac6
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1400-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
