### PR TITLE
Fixes #187 load variables and mixins in components

### LINKED ISSUE #187: Redo SASS imports to not reimport base every time

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by dgutride** [comment]
@pmuir - I pulled this branch to run and webpack is failing with: ERROR in Path must be a string. Received undefined

**Comment by pmuir** [comment]
Yeah I'm seeing that too. I will investigate.

**Comment by pmuir** [comment]
Pushed too many commits to the branch :-(

**Comment by pmuir** [comment]
Yes, that should remove that error.

**Pull request merged**
