### PR TITLE
fix(space-wizard): import github repo should import the repo in codeb…

### PR DESCRIPTION
**Pull request by corinnekrych**
…ases

Fixes https://github.com/fabric8io/fabric8-ui/issues/1479

### CODE REVIEW

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Comment by corinnekrych** [comment]
@mitchharpur As you've suggested I've moved the format logic to `scrubAppGeneratorResponse` method. I also rebased.
ok to merge?

**Comment by fabric8cd** [comment]
@corinnekrych snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1537-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
