### PR TITLE
Space wizard repo fixes

### PR DESCRIPTION
**Pull request by mitchharpur**
Fix
- Synchronize default repo name to be the space name ... for new space only
- Update fields to reflect project name id repo name
- Added field mapping for cleanup and ux changes for other fields
- calling text validation on change and not just enter

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8a7c8f649e749e0ac85810cd422cebbec25db4a6
  * Your subject line is longer than 50 characters

 * Commit: 4173623a724bfae81b9cd3c276a64d8f6fbf2de7
  * Your subject line is longer than 50 characters

 * Commit: 67b0e8bc4107ade0a833622dc8904ad86687c35f
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-887-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cfaf1d2435e6d56e6c1c2649ec1a99ce15c1d47f
  * Your subject line is longer than 50 characters

 * Commit: c21e359500018ca5a394df2c353e7581fd4ff173
  * Your subject line is longer than 50 characters

 * Commit: 8106e03ef3594165ac95f7ee31b924a965f2ee29
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-887-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
