### PR TITLE
fix(home): Updated to match latest mockups

### PR DESCRIPTION
**Pull request by dlabrecq**
screen shot 2017-04-25 at 11 47 08 am

FYI @catrobson @jryhanyc

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by jryhanyc** [comment]
@dlabrecq @catrobson Wow, this looks awesome!

**Comment by joshuawilson** [comment]
OpenShift logo is missing

**Comment by dlabrecq** [comment]
Need to update Webpack to copy svg files.

**Comment by mindreeper2420** [comment]
@dlabrecq can you add `padding-left: 20px;` and `padding-right: 20px;` to the `<p>` under the OpenShift.io logo? This will help with wrapping. Also remove the word "more" from "Learn more about OpenShift".

**Comment by dlabrecq** [comment]
Added the padding and cleaned up the text per Adam's comments.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by dlabrecq** [comment]
Still seeing the same issue with the snapshot -- will investigate.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by dlabrecq** [comment]
Apparently, there is a problem with fonts using svgs, so Jessica converted the svg image to png.

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1055-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
