### PR TITLE
fix(modals): update modal styles

### PR DESCRIPTION
**Pull request by mindreeper2420**
update modal styles to properly position Title and other elements

closes https://github.com/fabric8io/fabric8-ux/issues/507

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1603-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
