### PR TITLE
fix: add new space to recent list

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ba0f296cb117b0f0a675269a84dd49dfcb471c24
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fd772126e6d0e4eb27e9d4969e8472b0158e5752
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1153-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1153-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
