### PR TITLE
Update SpaceService to allow editing of spaces

### LINKED ISSUE #91: Extend SpacesService to edit spaces in the REST API backend.
**Description**

We need to extend the Angular service SpacesService to edit existing spaces using the spaces REST API. The space name should be used to identify the space.

**Implementation**

The SpacesService need to implement and expose a new public method to edit existing spaces.

**Reference**

User story - #55

### PR DESCRIPTION
**Pull request by VineetReynolds**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature. Fixes #91 to allow consumers of SpaceService to perform editing of spaces.

* **What is the current behavior?** (You can also link to an open issue here)

SpaceService does not support updates to space instances.

* **What is the new behavior (if this is a feature change)?**

A new method to support PATCH requests for space instance objects is created under SpaceService.

* **Other information**:

Builds on top of #90

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
Waiting for almighty-core PR to get merged.

**Comment by joshuawilson** [comment]
[test]

**Comment by VineetReynolds** [comment]
Closing this as this work has been subsumed into ngx-fabric8-wit entirely.

**Pull request closed without merging**
