### PR TITLE
fix (test): cat the test results log to stdout

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 33b9a40c5398a90efe039ad20c03c210c31ebbbc
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1219-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1219-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1219-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1219-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1219-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
