### PR TITLE
Update package.json ngx-login-client to 0.4.4

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge] lgtm

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5606d3fd3c90b13a8b099064f565c3c04ef977cb
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by rawlingsj** [comment]
@joshuawilson this is the PR you've already said shouldn't be merged, correct?  Maybe we should close this now.

Also one thing I've noticed is the json pretty print after updating the version has changed the tab intend of the package.json, I'll try and find if the groovy JSONBuilder can use 2 spaces and not 4 to avoid the formatting conflicts here.

But I think this is a good start?

**Comment by dgutride** [comment]
There is already a PR up to update ngx-login-client:  https://github.com/fabric8io/fabric8-ui/pull/233 and requires supporting changes in that PR before we can bump to 0.4.4

**Comment by rawlingsj** [comment]
@dgutride yeah this was an automated PR created as part of an upstream project dependency pipeline https://github.com/fabric8-ui/ngx-login-client/pull/14.  

We know there's an issue with the upgrade but were checking the CI gates would catch it.  

I think we can close this PR now.

**Comment by joshuawilson** [comment]
@rawlingsj it is nice to see that it works, that is cool. 

However, the update does 3 things I don't like. 
1) The indention as you mentioned
2) changed the order of the sections
3) makes everything not alphabetical

**Comment by rawlingsj** [comment]
That's fine, it was a first pass to get this kinda feedback!  I'd missed the order and alphabetical bits you mentioned.

I used groovy to parse the package.json, replace the version value and write the new new file before committing it.  I'm thinking we might be better off with a bit of old `sed` :).  Lemme have a play in the morning and see what options we have to address the three points you have and anything else that pops up.

**Pull request closed without merging**
