### PR TITLE
fix: change type from identities to users

### PR DESCRIPTION
**Pull request by pmuir**
DO NOT MERGE YET

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: befa85c5bc423a12414e382abb06996bc57aa774
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by sbose78** [comment]
Thanks for the PR @pmuir , let me test this with core and let you know.

**Comment by joshuawilson** [comment]
@pmuir please rebase

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: be757fbcd2ff200f6bd01b0be2ade138e0a26726
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
