### PR TITLE
fix: add authorization header to github requests

### PR DESCRIPTION
**Pull request by pmuir**
* this increases the request rate 10 fold and does it per user not per IP

~REQUIRES https://github.com/fabric8-ui/ngx-login-client/pull/43~

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1ba2c5835ad7fd5055f7d194391bbe54b9ccbd6a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 33aec5468b5648fd25fb806e57375ca9bfcc1997
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 33aec5468b5648fd25fb806e57375ca9bfcc1997
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-616.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
@pmuir I tried to deal with the conflicts but I couldn't do enough from github. Please rebase.

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-616.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-616.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 33aec5468b5648fd25fb806e57375ca9bfcc1997
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-616.int.rdu2c.fabric8.io

**Pull request merged**
