### PR TITLE
chore(build): include gpg keys in git repo

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

 * Commit: 6d0ea0e4e5c3b7671f72876492c808cb273eb757
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

 * Commit: b8056157d4bb00bb456a3ec3a22f312ddb6500db
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

 * Commit: 6fa15dc89400118781b2e12707ea4b456a16b1d3
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

 * Commit: 89d17cb334b6b9cac2a841774dbe16ef7973fa72
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bf5d46f51ea24a58e54084eef37a403079fa78d3
  * Your commit message does not contain a body

 * Commit: 6e5a8c7e4f2734c3e1963c6c25910e05004a3b61
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 276730fb0d58b4ce05cb4f0befb8003b420f45b1
  * Your commit message does not contain a body

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
@joshuawilson please review asap as this will stablise the build system

**Pull request merged**
