### PR TITLE
fix(pipeline): PR pipeline stability improvements and let's push a community image to dockerhub

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 52dfbd686dcf9a983c5eb45b28eb46e66a85ecd7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c6c5097da26f75c431089839f0960b5b3a4473ee
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 52dfbd686dcf9a983c5eb45b28eb46e66a85ecd7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ead471ec4b12210e7a471faa00fdea5e634153c2
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 52dfbd686dcf9a983c5eb45b28eb46e66a85ecd7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c230a4c2a6388867ab826d33488c7ae111d29c37
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 52dfbd686dcf9a983c5eb45b28eb46e66a85ecd7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a0aca7a12111ef92c153afa8ea4f5140b94e04eb
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a040ab9fa9ba1cb680d325a4354737b49698c3ca
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1314-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 59f4a4562f6b894043420d9fcb792afe1d0f8111
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1314-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1314-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
