### PR TITLE
Remove not existing space templates from space creation drop down

### PR DESCRIPTION
**Pull request by kwk**
This addresses @qodfathr 's comment on not having things in the UI that are not functional.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0a5ac9c5f95731095da6dbada1a22a4f57955065
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 385070f77e4e5ffb0fc764cf0c554a6d5ad7b83f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
Rejecting this as we are fixing this now and will address fake UI parts when we get to the "go public" date. No need to remove it yet.
We can save it for now in case we need it later.

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1421-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
Since we do not have a resolution in place for this I'm going to accept it. We can add the options back in when they are viable again.

**Pull request merged**
