### PR TITLE
fix: remove environments page

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9d61b9a15def03169f6840cb0c3bdd4d94b6a727
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
already done

**Comment by fabric8cd** [comment]
@pmuir snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1179-fabric8-ui.int.rdu2c.fabric8.io

**Pull request closed without merging**
