### PR TITLE
chore(space-wizard): ux tweaks gleaned from feedback

### PR DESCRIPTION
**Pull request by mitchharpur**
- makes a few ux tweaks and fixes based on feedback

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1444-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@mitchharpur why did you include package-lock.json?

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1444-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
