### PR TITLE
update readme so it renders correctly

### PR DESCRIPTION
**Pull request by maxandersen**
Fixes issue where semantic versioning was formatted
with non-markdown.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f634c85f76ec4a018108af023f9866ede9572f8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by maxandersen** [comment]
that gitcop is rather pedantic :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f23bdf0ca68a0f94a855e01aa8caf15a377c7f36
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
Note, your change should be a docs: not a fix: as there is no need to do a patch release for this...

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f23bdf0ca68a0f94a855e01aa8caf15a377c7f36
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3a71894383a8687badd143ac3a2295180842b722
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f23bdf0ca68a0f94a855e01aa8caf15a377c7f36
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3a71894383a8687badd143ac3a2295180842b722
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c3b260dc83c36eb5c93514a9c0d2b68058c9d52a
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f23bdf0ca68a0f94a855e01aa8caf15a377c7f36
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3a71894383a8687badd143ac3a2295180842b722
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c3b260dc83c36eb5c93514a9c0d2b68058c9d52a
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by pmuir** [comment]
Merged

**Pull request closed without merging**
