### PR TITLE
fix(space-wizard): add optional images to dropdowns

### PR DESCRIPTION
**Pull request by mitchharpur**
- adds pipeline images to the pipeline dropwdown
- adds stack images to stack dropdown

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 257392ab2145928895b8510004a7d17eeaa27d6f
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1135-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by catrobson** [comment]
Example of list view with expansion with a radio button selection:  choosepipeline_optionb

We should have a expansion based list view available for consumption as part of the ngx-widgets.

If you can't do this, just do a basic list with radio button selection that shows the pipelines without expansion capabilities to hide them.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e80e0023297743c677cef52865b707ba4ac67a82
  * Your subject line is longer than 50 characters

 * Commit: ec70df7320f295e05fa84bf89a4e1d671ae3b335
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1135-fabric8-ui.int.rdu2c.fabric8.io

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8555fe15e02102b3409e6893c356f692926d490b
  * Your subject line is longer than 50 characters

 * Commit: 9a3397d28474564cc049463329068362f10aa125
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1135-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
