### PR TITLE
Code guidelines cleanup

### PR DESCRIPTION
**Pull request by mindreeper2420**
This PR updates the CSS files to match the code guidelines as prescribed here: http://codeguide.co/#css. A subsequent PR will update the HTML files.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d89b2a958c90b1303853c3d86b3c60393166261d
  * Your subject line is longer than 50 characters

 * Commit: 7eb510254a156d3a5a05f9fb0109dabd9ba67683
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by mindreeper2420** [comment]
Space Wizard was not updated with this PR. Due to the complexity around that component (and it having various pieces throughout other components), it will be a separate PR.

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1308-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1308-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
