### PR TITLE
feat(codebases): Added additional features

### PR DESCRIPTION
**Pull request by dlabrecq**
Added additional features to the codebases page. This includes the ability to create a workspace, repo details from GitHub, various toast notifications, etc. All modified to work with Pete's router outlet.

NOTE: The listView component was also modified to support empty state, headers, etc. Therefore, this PR requires https://github.com/fabric8-ui/ngx-widgets/pull/63 to be merged first

screen shot 2017-04-03 at 10 54 56 am

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 017c408321a9f0740b3ac697e1e210fd863b3500
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: be617e646e4e88b2396c300e99e910b11ea8dc9d
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7f6cbf35c3951892a2cec3637b22f2091beaf1da
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: aa5c00db39f1ac86c06d6b360d09d8a9cfe949fa
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by joshuawilson** [comment]
[test]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9309c49d988e181a8d4d62f4160ca244b7a58061
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 02ae6aa33230de8d99f6f45349454564f760f45d
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e5c232bcfce0a68b2b900fed16a43ad7994996c5
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
