### PR TITLE
fix(spaces): updated Dashboard with new framing

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the Spaces dashboard with new framing to eliminate scrolling and set fixed heights for all cards. New f8-card component created.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-764-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-764-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
@mindreeper2420 Still seeing side scrolling on Space dashboard.

**Comment by mindreeper2420** [comment]
@joshuawilson should be fixed now. The problem is that there is code that overwrites behavior of the `<section>`, so anything with `.cards-pf` needs to be on a `<div>` instead.

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-764-fabric8-ui.int.rdu2c.fabric8.io

**Pull request merged**
