### PR TITLE
190

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
[test]

**Comment by pmuir** [comment]
@joshuawilson ready for review

**Comment by joshuawilson** [comment]
The tests still fail locally for me with.

[1] "loader" must be a string
[2] "loaders" at position 1 must be a String or an Object with properties: "loader": (String, required), "query": (Object, optional)
[3] "loaders" at position 2 must be a String or an Object with properties: "loader": (String, required), "query": (Object, optional)

**Comment by joshuawilson** [comment]
This still fails the tests locally but it fixes a lot of other stuff, so I'm going to merge it now. Then we can fix the broken stuff.

**Pull request merged**
