### PR TITLE
fix(placeholder): add selector placeholder

### PR DESCRIPTION
**Pull request by mindreeper2420**
add a selector placeholder for the Stack Recommendations widget

screen shot 2017-06-26 at 3 03 50 pm

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1602-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by invincibleJai** [comment]
@joshuawilson @mindreeper2420 Looks fine to me with recommendations 
screen shot 2017-06-27 at 4 56 02 pm

**Pull request merged**
