### PR TITLE
feat(space-wizard): add collapsible single select widget

### LINKED ISSUE #862: Space Wizard has the same tooltip/title message everywhere
No matter where I hover my mouse in the Space Wizard, I am presented with a tooltip/title message of 'Create new space'. If tooltips/title messages are used, they should be specific to given click points ('X' for close, buttons, etc.).

screen shot 2017-04-19 at 9 57 27 am

### PR DESCRIPTION
**Pull request by mitchharpur**
- refactor wizard single select into separate component in which the selections also have collapsible selections as per ux designs
- required field indicator is now red as per ux spec
- tooltip fixes

fixes #862 
improves fidelity to designs #541

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f9054ecb88ea13f9ee437db4b30d8f53841055b8
  * Your subject line is longer than 50 characters

 * Commit: 5dee833bf03e6bc7e14a6d0559c838258ade5452
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/fabric8io/fabric8-ui

---
This message was auto-generated by https://gitcop.com

**Comment by fabric8cd** [comment]
@mitchharpur snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1418-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
