### PR TITLE
fix(test): E2E test script fixed

### PR DESCRIPTION
**Pull request by rgarg1**
Pipeline builds are now auto triggered, and hence the test was failing. Fixed the test to PASS, but request a review to ensure the auto-trigger behavior is really intended.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1518-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1518-fabric8-ui.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
@rgarg1 please fix the conflict and rebase.
@ldimaggi please review.

**Comment by ldimaggi** [comment]
We can simply close this PR - it was made obsolete by this commit:

https://github.com/ldimaggi/fabric8-ui/commit/3d3438a7be6980164e3268281bb0979ca5847f18

**Pull request closed without merging**
